// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5Erfwe1yBiGmUdWf4-nMgbYsS2FitCw',
    appId: '1:8016838964:web:16ca13037eff21d1102561',
    messagingSenderId: '8016838964',
    projectId: 'social-app-d5fe3',
    authDomain: 'social-app-d5fe3.firebaseapp.com',
    storageBucket: 'social-app-d5fe3.appspot.com',
    measurementId: 'G-RCPH8LGF7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0o5oOwnXlzcfhzF5rZtacYCyIoOasxw',
    appId: '1:8016838964:android:e17f8954ae7c98e5102561',
    messagingSenderId: '8016838964',
    projectId: 'social-app-d5fe3',
    storageBucket: 'social-app-d5fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADklzZ3vt9twhjl1RLs09ZRysfcp-T9KM',
    appId: '1:8016838964:ios:e6c5d8b785f2fc34102561',
    messagingSenderId: '8016838964',
    projectId: 'social-app-d5fe3',
    storageBucket: 'social-app-d5fe3.appspot.com',
    androidClientId: '8016838964-1alcv7thnap0aqccli76s5eo8hf250k5.apps.googleusercontent.com',
    iosClientId: '8016838964-hjcgeatb7vbdfk05nve064gkj2s5f5ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADklzZ3vt9twhjl1RLs09ZRysfcp-T9KM',
    appId: '1:8016838964:ios:e6c5d8b785f2fc34102561',
    messagingSenderId: '8016838964',
    projectId: 'social-app-d5fe3',
    storageBucket: 'social-app-d5fe3.appspot.com',
    androidClientId: '8016838964-1alcv7thnap0aqccli76s5eo8hf250k5.apps.googleusercontent.com',
    iosClientId: '8016838964-hjcgeatb7vbdfk05nve064gkj2s5f5ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
